### ISSUE TITLE
Incompatibility with rich >= 9.5.0

### ISSUE THREAD

**Issue by jsf9k** [pycontribs/enrich#18]
[rich >= 9.5.0 appears to have some changes that break enrich](https://github.com/willmcgugan/rich/blob/master/CHANGELOG.md#950---2020-12-18).  This in turn is breaking molecule, as seen in ansible-community/molecule#3010.

**Comment by ssbarnea** [comment]
True. A PR would have being easier I guess :D

**Comment by ssbarnea** [comment]
Closed by #21

**Comment by jsf9k** [comment]
Thank you @ssbarnea!
